version: '3.9'
services:
  osticket_db:
    image: mariadb:11.3-jammy
    container_name: OsTicket_DB
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      - MYSQL_ROOT_PASSWORD=EnZ8d5ajuEG87v2nSdC
      - MYSQL_USER=some_user
      - MYSQL_PASSWORD=some_password
      - MYSQL_DATABASE=my_database_name
    volumes:
      - /volume1/docker/osticket:/var/lib/mysql:rw
    restart: on-failure:5
 
  osticket:
    image: devinsolutions/osticket:latest
    container_name: OsTicket
    ports:
      - 6784:80
    depends_on:
      - osticket_db
    environment:
       MYSQL_USER: osticket
       MYSQL_PASSWORD: 1V9TZMSKZ8MFGUEBD
       MYSQL_DATABASE: osticket
       MYSQL_HOST: osticket_db
       INSTALL_SECRET: xgudkagdsrlkaxkiyxoflredkebxzlxu
       INSTALL_URL: http://localhost
       INSTALL_NAME: SurePay Helpdesk
       ADMIN_USERNAME: iamtutumo
       ADMIN_PASSWORD: surepayltd
       ADMIN_FIRSTNAME: Tutu
       ADMIN_LASTNAME: Moses
       ADMIN_EMAIL: etu.moses@gmail.com
       CRON_INTERVAL: 1
       SMTP_USER: etu.moses@gmail.com
       SMTP_PASSWORD: Your-own-app-password
       SMTP_HOST: smtp.gmail.com
       SMTP_PORT: 587
       SMTP_FROM: etu.moses@gmail.com
       SMTP_TLS: 1
    restart: on-failure:5






#### Moving files

    docker exec -it c8d17264d58e /bin/sh
    docker cp /root/images/. c8d17264d58e:/var/www/html/images
    docker cp /root/include/. c8d17264d58e:/var/www/html/include
    docker cp /root/scp/. c8d17264d58e:/var/www/html/scp
    docker cp /root/css/. c8d17264d58e:/var/www/html/css
    docker cp /root/assets/. c8d17264d58e:/var/www/html/assets


